// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CursorPosition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PhoneRemote.Protobuf.ProtoModels {

  /// <summary>Holder for reflection information generated from CursorPosition.proto</summary>
  public static partial class CursorPositionReflection {

    #region Descriptor
    /// <summary>File descriptor for CursorPosition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CursorPositionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDdXJzb3JQb3NpdGlvbi5wcm90bxILUGhvbmVSZW1vdGUiKAoOQ3Vyc29y",
            "UG9zaXRpb24SCgoCZFgYASABKAUSCgoCZFkYAiABKAVCI6oCIFBob25lUmVt",
            "b3RlLlByb3RvYnVmLlByb3RvTW9kZWxzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PhoneRemote.Protobuf.ProtoModels.CursorPosition), global::PhoneRemote.Protobuf.ProtoModels.CursorPosition.Parser, new[]{ "DX", "DY" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CursorPosition : pb::IMessage<CursorPosition> {
    private static readonly pb::MessageParser<CursorPosition> _parser = new pb::MessageParser<CursorPosition>(() => new CursorPosition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CursorPosition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PhoneRemote.Protobuf.ProtoModels.CursorPositionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CursorPosition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CursorPosition(CursorPosition other) : this() {
      dX_ = other.dX_;
      dY_ = other.dY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CursorPosition Clone() {
      return new CursorPosition(this);
    }

    /// <summary>Field number for the "dX" field.</summary>
    public const int DXFieldNumber = 1;
    private int dX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DX {
      get { return dX_; }
      set {
        dX_ = value;
      }
    }

    /// <summary>Field number for the "dY" field.</summary>
    public const int DYFieldNumber = 2;
    private int dY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DY {
      get { return dY_; }
      set {
        dY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CursorPosition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CursorPosition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DX != other.DX) return false;
      if (DY != other.DY) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DX != 0) hash ^= DX.GetHashCode();
      if (DY != 0) hash ^= DY.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DX != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DX);
      }
      if (DY != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DX);
      }
      if (DY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DY);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CursorPosition other) {
      if (other == null) {
        return;
      }
      if (other.DX != 0) {
        DX = other.DX;
      }
      if (other.DY != 0) {
        DY = other.DY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DX = input.ReadInt32();
            break;
          }
          case 16: {
            DY = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
