// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CursorAction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PhoneRemote.Protobuf.ProtoModels {

  /// <summary>Holder for reflection information generated from CursorAction.proto</summary>
  public static partial class CursorActionReflection {

    #region Descriptor
    /// <summary>File descriptor for CursorAction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CursorActionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJDdXJzb3JBY3Rpb24ucHJvdG8SC1Bob25lUmVtb3RlImIKDEN1cnNvckFj",
            "dGlvbhIKCgJkWBgBIAEoBRIKCgJkWRgCIAEoBRITCgthY3Rpb25GbGFncxgD",
            "IAEoDRISCgphY3Rpb25EYXRhGAQgASgFEhEKCWV4dHJhSW5mbxgFIAEoBUIj",
            "qgIgUGhvbmVSZW1vdGUuUHJvdG9idWYuUHJvdG9Nb2RlbHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PhoneRemote.Protobuf.ProtoModels.CursorAction), global::PhoneRemote.Protobuf.ProtoModels.CursorAction.Parser, new[]{ "DX", "DY", "ActionFlags", "ActionData", "ExtraInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CursorAction : pb::IMessage<CursorAction> {
    private static readonly pb::MessageParser<CursorAction> _parser = new pb::MessageParser<CursorAction>(() => new CursorAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CursorAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PhoneRemote.Protobuf.ProtoModels.CursorActionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CursorAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CursorAction(CursorAction other) : this() {
      dX_ = other.dX_;
      dY_ = other.dY_;
      actionFlags_ = other.actionFlags_;
      actionData_ = other.actionData_;
      extraInfo_ = other.extraInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CursorAction Clone() {
      return new CursorAction(this);
    }

    /// <summary>Field number for the "dX" field.</summary>
    public const int DXFieldNumber = 1;
    private int dX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DX {
      get { return dX_; }
      set {
        dX_ = value;
      }
    }

    /// <summary>Field number for the "dY" field.</summary>
    public const int DYFieldNumber = 2;
    private int dY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DY {
      get { return dY_; }
      set {
        dY_ = value;
      }
    }

    /// <summary>Field number for the "actionFlags" field.</summary>
    public const int ActionFlagsFieldNumber = 3;
    private uint actionFlags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ActionFlags {
      get { return actionFlags_; }
      set {
        actionFlags_ = value;
      }
    }

    /// <summary>Field number for the "actionData" field.</summary>
    public const int ActionDataFieldNumber = 4;
    private int actionData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActionData {
      get { return actionData_; }
      set {
        actionData_ = value;
      }
    }

    /// <summary>Field number for the "extraInfo" field.</summary>
    public const int ExtraInfoFieldNumber = 5;
    private int extraInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ExtraInfo {
      get { return extraInfo_; }
      set {
        extraInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CursorAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CursorAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DX != other.DX) return false;
      if (DY != other.DY) return false;
      if (ActionFlags != other.ActionFlags) return false;
      if (ActionData != other.ActionData) return false;
      if (ExtraInfo != other.ExtraInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DX != 0) hash ^= DX.GetHashCode();
      if (DY != 0) hash ^= DY.GetHashCode();
      if (ActionFlags != 0) hash ^= ActionFlags.GetHashCode();
      if (ActionData != 0) hash ^= ActionData.GetHashCode();
      if (ExtraInfo != 0) hash ^= ExtraInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DX != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DX);
      }
      if (DY != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DY);
      }
      if (ActionFlags != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ActionFlags);
      }
      if (ActionData != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ActionData);
      }
      if (ExtraInfo != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ExtraInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DX);
      }
      if (DY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DY);
      }
      if (ActionFlags != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ActionFlags);
      }
      if (ActionData != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActionData);
      }
      if (ExtraInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExtraInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CursorAction other) {
      if (other == null) {
        return;
      }
      if (other.DX != 0) {
        DX = other.DX;
      }
      if (other.DY != 0) {
        DY = other.DY;
      }
      if (other.ActionFlags != 0) {
        ActionFlags = other.ActionFlags;
      }
      if (other.ActionData != 0) {
        ActionData = other.ActionData;
      }
      if (other.ExtraInfo != 0) {
        ExtraInfo = other.ExtraInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DX = input.ReadInt32();
            break;
          }
          case 16: {
            DY = input.ReadInt32();
            break;
          }
          case 24: {
            ActionFlags = input.ReadUInt32();
            break;
          }
          case 32: {
            ActionData = input.ReadInt32();
            break;
          }
          case 40: {
            ExtraInfo = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
